const currencies = {
  "USD": "United States Dollars",
  "EUR": "Euro",
  "GBP": "United Kingdom Pounds",
  "DZD": "Algeria Dinars",
  "ARP": "Argentina Pesos",
  "AUD": "Australia Dollars",
  "ATS": "Austria Schillings",
  "BSD": "Bahamas Dollars",
  "BBD": "Barbados Dollars",
  "BEF": "Belgium Francs",
  "BMD": "Bermuda Dollars",
  "BRR": "Brazil Real",
  "BGL": "Bulgaria Lev",
  "CAD": "Canada Dollars",
  "CLP": "Chile Pesos",
  "CNY": "China Yuan",
  "CYP": "Cyprus Pounds",
  "CSK": "Czech Republic Koruna",
  "DKK": "Denmark Kroner",
  "NLG": "Dutch Guilders",
  "EGP": "Egypt Pounds",
  "FJD": "Fiji Dollars",
  "FIM": "Finland Markka",
  "FRF": "France Francs",
  "DEM": "Germany Deutsche Marks",
  "GRD": "Greece Drachmas",
  "HKD": "Hong Kong Dollars",
  "HUF": "Hungary Forint",
  "ISK": "Iceland Krona",
  "INR": "India Rupees",
  "IDR": "Indonesia Rupiah",
  "IEP": "Ireland Punt",
  "ILS": "Israel New Shekels",
  "ITL": "Italy Lira",
  "JMD": "Jamaica Dollars",
  "JPY": "Japan Yen",
  "JOD": "Jordan Dinar",
  "LBP": "Lebanon Pounds",
  "LUF": "Luxembourg Francs",
  "MYR": "Malaysia Ringgit",
  "MXP": "Mexico Pesos",
  "NZD": "New Zealand Dollars",
  "NOK": "Norway Kroner",
  "PKR": "Pakistan Rupees",
  "PHP": "Philippines Pesos",
  "PLZ": "Poland Zloty",
  "PTE": "Portugal Escudo",
  "ROL": "Romania Leu",
  "RUR": "Russia Rubles",
  "SAR": "Saudi Arabia Riyal",
  "XAG": "Silver Ounces",
  "SGD": "Singapore Dollars",
  "SKK": "Slovakia Koruna",
  "ZAR": "South Africa Rand",
  "KRW": "South Korea Won",
  "ESP": "Spain Pesetas",
  "XDR": "Special Drawing Right (IMF)",
  "SDD": "Sudan Dinar",
  "SEK": "Sweden Krona",
  "CHF": "Switzerland Francs",
  "TWD": "Taiwan Dollars",
  "THB": "Thailand Baht",
  "TTD": "Trinidad and Tobago Dollars",
  "TRL": "Turkey Lira",
  "VEB": "Venezuela Bolivar",
  "ZMK": "Zambia Kwacha",
  "XCD": "Eastern Caribbean Dollars",
  "XAU": "Gold Ounces",
  "XPD": "Palladium Ounces",
  "XPT": "Platinum Ounces",
}

export default currencies